include: package:very_good_analysis/analysis_options.3.0.2.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    literal_only_boolean_expressions: false
    require_trailing_commas: false
    comment_references: false
    only_throw_errors: false
