name: somaya_gallery
version: 1.0.0
description: My new Flutter app
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  window_manager: ^0.3.6
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.0
  firebase_core: ^2.15.1
  go_router: ^7.1.1
  url_launcher: ^6.1.12
  internet_connection_checker: ^1.0.0+1
#  universal_html: ^2.2.2
  scrolls_to_top: ^2.1.0
  flutter_helper_utils: ^1.4.8

  authentication_repository:
    path: ./packages/authentication_repository
  hive_api:
    path: ./packages/hive_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter: 
  uses-material-design: true
  generate: true
