name: flutter_starter
version: 1.0.0
description: My new Flutter app
publish_to: none

environment: 
  sdk: '>=2.18.0 <3.0.0'
  flutter: 3.3.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hydrated_bloc: 9.0.0
  path_provider: ^2.0.11
  firebase_core: ^2.2.0
  intl: ^0.17.0
  quiver: ^3.1.0
  http: ^0.13.5
  go_router: ^5.1.5
  url_launcher: ^6.1.6
  universal_html: ^2.0.8
  internet_connection_checker: ^1.0.0+1

  authentication_repository:
    path: ./packages/authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter: 
  uses-material-design: true
  generate: true
