name: flutter_starter
version: 1.0.0
description: My new Flutter app
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  window_manager: ^0.3.1
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.13
  firebase_core: ^2.7.1
  intl: ^0.17.0
  go_router: ^6.2.0
  url_launcher: ^6.1.10
  internet_connection_checker: ^1.0.0+1
  universal_html: ^2.0.9
  scrolls_to_top: ^2.1.0

  authentication_repository:
    path: ./packages/authentication_repository
  flutter_helper:
   git:
    url: https://github.com/omar-hanafy/flutter-helper.git
    ref: main # branch name

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter: 
  uses-material-design: true
  generate: true
